name: s_animated_tabs
description: A professional and highly customizable animated tab switcher widget for Flutter that provides smooth, polished animations.
issue_tracker: https://github.com/SoundSliced/s_animated_tabs/issues
repository: https://github.com/SoundSliced/s_animated_tabs
version: 2.1.1
homepage: https://github.com/SoundSliced/s_animated_tabs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
